#pragma once

#define NRF_LOG_ENABLED 1
#define NRF_LOG_DEFAULT_LEVEL 4

#define NRF_LOG_BACKEND_SERIAL_USES_RTT 1
#define NRF_LOG_BACKEND_SERIAL_USES_UART 0

#define APP_MAILBOX_ENABLED 1

#define UART_CONFIG_LOG_ENABLED 0
#define UART_CONFIG_LOG_LEVEL 0